import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css';
import MyLayout from '../../components/my/MyLayout';
import CreatePost from '../../components/my/CreatePost';

export default function MyHome() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Kowloon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <CreatePost />        


    </div>
  )
}

MyHome.getLayout = function getLayout(page) {
    return (
      <MyLayout>
        {page}
      </MyLayout>
    )
  }
  
