import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import axios from "axios";
import Kowloon from "../modules/kowloon";
import connectMongo from "../utils/connectMongo";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import {
  FaCheckSquare,
  FaAlignJustify,
  FaLink,
  FaCameraRetro,
} from "react-icons/fa";
dayjs.extend(relativeTime);

export async function getServerSideProps(context) {
  await connectMongo();
  const settings = await Kowloon.settings();
  return { props: { settings } };
}

export default function Home(props) {
  console.log(props);
  const [posts, getPosts] = useState([]);

  const loadPosts = async () => {
    try {
      let response = await axios.get("/api/posts");
      getPosts(response.data.posts);
    } catch (e) {
      // console.log(e.message);
    }
  };

  useEffect(() => {
    loadPosts();
  }, []);

  return (
    <div className="container mx-auto bg-gray-200 text-black">
      <Head>
        <title>{props.settings.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid grid-cols-12 w-full h-screen content-start">
        <h1 className="font-bold text-2xl text-center col-span-12 mt-2">
          {props.settings.name}
        </h1>
        <h2 className="text-center col-span-12 text-gray-500 mb-8 text-sm">
          {/* {props.settings.description} */}
        </h2>
        <div className="col-span-3"></div>
        {posts.length > 0 ? (
          <ul className="col-span-6">
            {posts.map((post, i) => {
              console.log(dayjs(post.createdAt).fromNow());
              return (
                <li
                  className={`post card mb-4 w-full bg-white text-black`}
                  key={i}
                >
                  <div className={`card-body w-full`}>
                    {post.title ? (
                      <div className="post-title font-bold text-lg">
                        {post.link ? (
                          <a href={post.link} target="_new">
                            {post.title}
                          </a>
                        ) : (
                          `${post.title}`
                        )}
                      </div>
                    ) : (
                      ""
                    )}
                    <div
                      className="mx-2"
                      dangerouslySetInnerHTML={{
                        __html: post.content.html
                          ? post.content.html
                          : post.content.text,
                      }}
                    ></div>
                    <div className="card-actions text-sm mx-2 text-gray-400 justify-end">
                      <span className="font-bold" title={post.postType}>
                        {post.postType == "status" ? <FaCheckSquare /> : ""}
                        {post.postType == "post" ? <FaAlignJustify /> : ""}
                        {post.postType == "media" ? <FaCameraRetro /> : ""}
                        {post.postType == "link" ? <FaLink /> : ""}
                      </span>{" "}
                      by
                      {post.author.username} |&nbsp;
                      {dayjs(post.createdAt).fromNow()}
                    </div>
                  </div>
                </li>
              );
            })}
          </ul>
        ) : (
          "Loading..."
        )}
      </main>
    </div>
  );
}
