import Head from "next/head";
import { useState } from "react";
import axios from "axios";
import { setCookie } from 'cookies-next';
import { useRouter } from 'next/router';




export function getServerSideProps(context) {

  return {
    props: {
      domain: context.req.headers.host
    }
  };

 }

export default function Install(props) {
  const router = useRouter();
  const [siteName, setSiteName] = useState("");
  const [siteUrl, setSiteUrl] = useState(props.domain || "");
  const [siteDescription, setSiteDescription] = useState("");
  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [displayname, setDisplayname] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  
  const installKowloon = async (e) => {
    e.preventDefault();
    const body =
    {
      settings: {
        name: siteName,
        url: siteUrl,
        description: siteDescription
      },
      user: {
        username, email, displayname, password
      }
    }
  
    const response = await axios.post("/api/install", body);
    if (response.data.error) {
      const error = response.data.error;
      console.log(error);
    } else {
      const user = response.data.user;
      router.push('/login?install=true')
    }
  }

  return (
    <>

      <Head>
        <title>Kowloon | Install</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2 className="font-bold text-xl mb-8 text-center">Install Kowloon</h2>
        <form onSubmit={installKowloon} className="w-1/2 mx-auto">
          <div className="form-control mb-8">
            <label htmlFor="name" className="label">Site Name</label>
            <input className="input input-bordered" id="name" name="name" onChange={(e) => setSiteName(e.target.value)} value={siteName} />
          </div>
          <div className="form-control mb-8">
            <label htmlFor="description" className="label">Site Description</label>
            <textarea className="textarea textarea-bordered h-24" id="description" name="description" onChange={(e) => setSiteDescription(e.target.value)} value={siteDescription}></textarea>
          </div>

          <div className="form-control mb-8">
            <label htmlFor="url" className="label">Site Domain</label>
            <input className="input input-bordered" id="url" name="url" value={siteUrl} onChange={(e) => setSiteUrl(e.target.value)}/>
          </div>
          <hr className="border-b-1 border-black mt-12 mb-8" />
          <h3 className="font-bold text-lg mb-8">Create User</h3>
          <div className="form-control mb-8">
            <label htmlFor="username" className="label">Username</label>
            <input className="input input-bordered" id="username" name="username" value={username} onChange={(e) => setUsername(e.target.value)}/>
          </div>
          <div className="form-control mb-8">
            <label htmlFor="email" className="label">Email</label>
            <input type="email" className="input input-bordered" id="email" name="email" value={email} onChange={(e) => setEmail(e.target.value)}/>
          </div>
          <div className="form-control mb-8">
            <label htmlFor="displayname" className="label">Display Name</label>
            <input className="input input-bordered" id="displayname" name="displayname" value={displayname} onChange={(e) => setDisplayname(e.target.value)}/>
          </div>
          <div className="form-control mb-8">
            <label htmlFor="password" className="label">Password</label>
            <input type={showPassword ? "text" : "password"} className="input input-bordered" id="username" name="username" value={password} onChange={(e) => setPassword(e.target.value)} />
            <div className="text-right">
             Show password? <input type="checkbox" checked={showPassword} className="checkbox mt-2" onChange={(e) => setShowPassword(e.target.checked)} />
              </div>
          </div>
          <div className="form-control text-right  mb-8">
            <button type='submit' className="btn btn-lg">Create Site</button>
        </div>
        </form>
      </main>
      </>
  );
}
