import LoginForm from "../components/my/LoginForm";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MyLayout from "../components/my/MyLayout";
import { getCookie, getCookies } from "cookies-next";
import { useRouter } from "next/router";

export function getServerSideProps(context) {
  // const props = context.req.query.install ? { install: true } : {};
  const props = {};
  return { props };
}
export default function Login(props) {
  const router = useRouter();
  console.log(router.query);
  return (
    <div className={styles.container}>
      <Head>
        <title>Kowloon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="grid w-full grid-cols-8">
        <div className="col-span-2"></div>

        <div className="col-span-4">
          <h1 className="text-xl font-bold text-center mt-4 col-span-2">
            Kowloon
          </h1>
          {router.query.install ? (
            <div className="card bg-amber-200 p-8 text-center">
              <h1 className="card-title">Install complete!</h1>
            </div>
          ) : (
            ""
          )}
          <LoginForm />
        </div>
      </main>
    </div>
  );
}
