import LoginForm from "../components/my/LoginForm"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import MyLayout from '../components/my/MyLayout';
import { getCookie, getCookies } from 'cookies-next';
export default function Login(props) {

    
    return (
        <div className={styles.container}>
        <Head>
          <title>Kowloon</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <h1 className="text-xl font-bold text-center mt-4">Kowloon</h1>
        <main className='grid w-full grid-cols-8'>
          <div className='col-span-2'>
          </div>
  
            <div className='col-span-4'>
            <LoginForm />   
          </div>
          </main>
  
      </div>
    )

}